/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.midea.VadAsr;

public class LogmmseVar {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LogmmseVar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogmmseVar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_LogmmseVar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LogmmseVar() {
    this(PocketSphinxJNI.new_LogmmseVar(), true);
  }

  public void logmmseinit() {
    PocketSphinxJNI.LogmmseVar_logmmseinit(swigCPtr, this);
  }

  public String logmmsedenosebufall(short[] sigBuf, int BufSize, Config config, int threshold, String orderfilename) {
    return PocketSphinxJNI.LogmmseVar_logmmsedenosebufall(swigCPtr, this, sigBuf, BufSize, Config.getCPtr(config), config, threshold, orderfilename);
  }

  public int noiseestimatebufall(short[] sigBuf, int BufSize) {
    return PocketSphinxJNI.LogmmseVar_noiseestimatebufall(swigCPtr, this, sigBuf, BufSize);
  }

}
