/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.midea.VadAsr;

public class PocketSphinxJNI {
  public final static native long new_LogmmseVar();
  public final static native void delete_LogmmseVar(long jarg1);
  public final static native void LogmmseVar_logmmseinit(long jarg1, LogmmseVar jarg1_);
  public final static native String LogmmseVar_logmmsedenosebufall(long jarg1, LogmmseVar jarg1_, short[] jarg2, int jarg3, long jarg4, Config jarg4_, int jarg5, String jarg6);
  public final static native int LogmmseVar_noiseestimatebufall(long jarg1, LogmmseVar jarg1_, short[] jarg2, int jarg3);
}
