/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.midea.VadAsr;

public class SphinxBaseJNI {
  public final static native long new_Config();
  public final static native void delete_Config(long jarg1);
  public final static native void Config_setString(long jarg1, Config jarg1_, String jarg2, String jarg3);
  public final static native void Config_setFloat(long jarg1, Config jarg1_, String jarg2, double jarg3);
}
